name: Data Platform CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  data-platform-validation:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install dbt-core
          pip install dbt-snowflake
          pip install sqlfluff

      - name: Create dummy dbt profile
        run: |
          mkdir -p ~/.dbt
          echo "edp_dbt:
            target: dev
            outputs:
              dev:
                type: snowflake
                account: dummy
                user: dummy
                password: dummy
                role: dummy
                database: dummy
                warehouse: dummy
                schema: dummy
                threads: 1" > ~/.dbt/profiles.yml

      - name: Validate dbt Project
        run: |
          cd edp_dbt
          dbt parse

      - name: Lint SQL Files
        run: |
          sqlfluff lint sql_platform